import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TableDataPosts from "./components/TableDataPosts";
import DelLastWord from "./components/DelLastWord";
import ActualHourButton from "./components/ActualHourButton";
import VowelCounter from "./components/VowelCounter";
import FormWithModal from "./components/FormWithModal";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h3>Hello! I am the first technical test in a long long time</h3>
          <br></br>
          <TableDataPosts></TableDataPosts>
          <br></br>
          <DelLastWord></DelLastWord>
          <br></br>
          <ActualHourButton></ActualHourButton>
          <br></br>
          <br></br>
          <VowelCounter></VowelCounter>
          <br></br>
          <FormWithModal></FormWithModal>
        </div>
      </main>
    </>
  );
}
